const SERVER_URL = "http://127.0.0.1:8080";
const URLS = {
    genre: SERVER_URL + "/genre",
    genres: SERVER_URL + "/genres",
    tag: SERVER_URL + "/tag",
    tags: SERVER_URL + "/tags",
    book: SERVER_URL + "/book",
    books: SERVER_URL + "/books",
    booksByTitle: SERVER_URL + "/books/by-title",
    booksByAll: SERVER_URL + "/books/by-all",
    publishingHouses: SERVER_URL + "/publishing-houses",
    publishingHouse: SERVER_URL + "/publishing-house",
    author: SERVER_URL + "/author",
    authors: SERVER_URL + "/authors",
    authorsByAll: SERVER_URL + "/authors/by-all",
    authorship: SERVER_URL + "/authorship",
    authorships: SERVER_URL + "/authorships",
    bookGenreByBook: SERVER_URL + "/book-genres/by-book-id",
    bookGenre: SERVER_URL + "/book-genre",
    bookGenres: SERVER_URL + "/book-genres",
    bookTag: SERVER_URL + "/book-tag",
    bookTags: SERVER_URL + "/book-tags",
    bookTagByBook: SERVER_URL + "/book-tags/by-book-id",
    authorshipByBook: SERVER_URL + "/authorships/by-book-id",
    authorshipByAuthor: SERVER_URL + "/authorships/by-author-id",
    bookDelivery: SERVER_URL + "/book-delivery",
    bookDeliveries: SERVER_URL + "/book-deliveries",
    delivery: SERVER_URL + "/delivery",
    deliveries: SERVER_URL + "/deliveries",
    deliveriesByAll: SERVER_URL + "/deliveries/by-all",
    bookBorrowing: SERVER_URL + "/book-borrowing",
    bookBorrowings: SERVER_URL + "/book-borrowings",
    bookBorrowingsByAll: SERVER_URL + "/book-borrowings/by-all",
    customer: SERVER_URL + "/customer",
    customers: SERVER_URL + "/customers",
    customersByAll: SERVER_URL + "/customers/by-all",
    monthStatistic: SERVER_URL + "/month-statistic",
    monthStatistics: SERVER_URL + "/month-statistics",
    monthStatisticsByPeriod: SERVER_URL + "/month-statistics/by-month-date-period",
    bookDeliveriesByDelivery: SERVER_URL + "/book-deliveries/by-delivery-id",
}
const indexProperties = [
    { "title": "Book management", "img": "../Images/book.png", "list": ["View books", "Search books", "Add new books", "Borrow books"], "location": "book.html" },
    { "title": "Author management", "img": "../Images/writers.png", "list": ["View authors", "Search authors and books by author", "Add new author"], "location": "author.html" },
    { "title": "Customer management", "img": "../Images/customers.png", "list": ["View customers", "Search customers", "Add new customer", "Return book"], "location": "customer.html" },
    { "title": "Library statistics", "img": "../Images/statistic.png", "list": ["Borrowing statistic", "Delivery statistic", "Recommendations for purchase"], "location": "statistic.html" },
    { "title": "Other", "img": "../Images/functions.png", "list": ["Genres", "Tags", "Publishing houses"], "location": "other.html" },
]