const SERVER_URL = "http://127.0.0.1:8080";
const URLS = {
    genre: SERVER_URL + "/genre",
    genres: SERVER_URL + "/genres",
    tag: SERVER_URL + "/tag",
    tags: SERVER_URL + "/tags",
    book: SERVER_URL + "/book",
    books: SERVER_URL + "/books",
    publishingHouses: SERVER_URL + "/publishing-houses",
    publishingHouse: SERVER_URL + "/publishing-house",
    author: SERVER_URL + "/author",
    authors: SERVER_URL + "/authors",
    authorship: SERVER_URL + "/authorship",
    authorships: SERVER_URL + "/authorships",
    bookGenreByBook: SERVER_URL + "/book-genres/by-book-id",
    bookGenre: SERVER_URL + "/book-genre",
    bookGenres: SERVER_URL + "/book-genres",
    bookTag: SERVER_URL + "/book-tag",
    bookTags: SERVER_URL + "/book-tags",
    bookTagByBook: SERVER_URL + "/book-tags/by-book-id",
    authorshipByBook: SERVER_URL + "/authorships/by-book-id"
}